//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStoreModel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupons
    {
        public int CouponID { get; set; }
        public string CouponName { get; set; }
        public decimal CouponDiscount { get; set; }
        public Nullable<System.DateTime> CouponExpiry { get; set; }
        public bool Active { get; set; }
        public Nullable<decimal> MinimumPurchase { get; set; }
    }
}
