
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineStoreModel.Context
{

using System;
    using System.Collections.Generic;
    
public partial class ProductRating
{

    public int productRatingID { get; set; }

    public Nullable<int> productID { get; set; }

    public Nullable<decimal> avgRating { get; set; }

    public Nullable<int> numOfRating { get; set; }



    public virtual Products Products { get; set; }

}

}
