
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineStoreModel.Context
{

using System;
    using System.Collections.Generic;
    
public partial class Products
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Products()
    {

        this.CART = new HashSet<CART>();

        this.ProductImages = new HashSet<ProductImages>();

        this.OrderDetails = new HashSet<OrderDetails>();

        this.Rating = new HashSet<Rating>();

        this.ProductRating = new HashSet<ProductRating>();

    }


    public int ProductID { get; set; }

    public string ProductName { get; set; }

    public string ProductDescription { get; set; }

    public Nullable<decimal> ProductPrice { get; set; }

    public Nullable<int> OwnerID { get; set; }

    public Nullable<bool> Availability { get; set; }

    public Nullable<bool> isDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CART> CART { get; set; }

    public virtual Owner Owner { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductImages> ProductImages { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetails> OrderDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rating> Rating { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductRating> ProductRating { get; set; }

}

}
