
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineStoreModel.Context
{

using System;
    using System.Collections.Generic;
    
public partial class RatingDetails
{

    public int ratingDetailsID { get; set; }

    public Nullable<int> ratingID { get; set; }

    public string review { get; set; }

    public string ratingNumber { get; set; }

    public Nullable<int> helpfulCount { get; set; }



    public virtual Rating Rating { get; set; }

}

}
