
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineStoreModel.Context
{

using System;
    using System.Collections.Generic;
    
public partial class Rating
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Rating()
    {

        this.RatingDetails = new HashSet<RatingDetails>();

        this.HelpfulReview = new HashSet<HelpfulReview>();

    }


    public int ratingID { get; set; }

    public int productID { get; set; }

    public int customerID { get; set; }

    public Nullable<bool> havePurchased { get; set; }

    public Nullable<System.DateTime> reviewDate { get; set; }



    public virtual Customers Customers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RatingDetails> RatingDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HelpfulReview> HelpfulReview { get; set; }

    public virtual Products Products { get; set; }

}

}
