
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineStoreModel.Context
{

using System;
    using System.Collections.Generic;
    
public partial class SubCategoryImage
{

    public int subCategoryImageID { get; set; }

    public Nullable<int> subCategoryID { get; set; }

    public string fileName { get; set; }



    public virtual SubCategory SubCategory { get; set; }

}

}
